import {formatStudent} from './auth.routes.js';
import express from 'express';import pool from '../config/db.js';import {asyncRoute,adminOnly} from '../middleware/auth.js';import {drop} from '../services/enrollment.js';import {calculateGrade,ApiError,text} from '../services/rules.js';import {randomUUID} from 'node:crypto';
const router=express.Router();router.use(adminOnly);
router.get('/overview',asyncRoute(async(req,res)=>{
 const [[students],[faculty],[courses],[active],[dropped],[sections],[departments],[waiting]]=await Promise.all([pool.query('SELECT COUNT(*) n FROM students'),pool.query('SELECT COUNT(*) n FROM faculty'),pool.query('SELECT COUNT(*) n FROM courses'),pool.query("SELECT COUNT(*) n FROM enrollments WHERE status='Enrolled'"),pool.query("SELECT COUNT(*) n FROM enrollments WHERE status='Dropped'"),pool.query(`SELECT cs.*,c.course_code,c.course_name,COUNT(e.id) AS filled_seats,cs.total_seats-COUNT(e.id) AS available_seats FROM course_sections cs JOIN courses c ON c.id=cs.course_id LEFT JOIN enrollments e ON e.section_id=cs.id AND e.status='Enrolled' GROUP BY cs.id,cs.course_id,cs.section_number,cs.section_name,cs.faculty_id,cs.faculty_name,cs.faculty_email,cs.classroom,cs.schedule,cs.total_seats,c.course_code,c.course_name ORDER BY c.course_code,cs.section_number`),pool.query('SELECT department,COUNT(*) AS student_count FROM students GROUP BY department'),pool.query("SELECT COUNT(*) n FROM waitlist WHERE status='Waiting'")]);
 res.json({success:true,stats:{totalStudents:students[0].n,totalFaculty:faculty[0].n,totalCourses:courses[0].n,totalActiveEnrollments:active[0].n,totalDroppedEnrollments:dropped[0].n,totalSections:sections.length,totalWaitlisted:waiting[0].n},sections,departments});
}));
router.get('/students',asyncRoute(async(req,res)=>{
 const [students]=await pool.query('SELECT s.*,v.current_gpa,v.completed_credits,v.attendance_rate  ,ch.cluster_id,ch.locked cluster_locked,cl.name cluster_name,cl.code cluster_code,o.value cgpa_override,o.reason cgpa_reason FROM students s JOIN v_student_academic_summary v ON v.student_id=s.id LEFT JOIN student_cluster_choices ch ON ch.student_id=s.id AND ch.semester=s.semester LEFT JOIN academic_clusters cl ON cl.id=ch.cluster_id LEFT JOIN cgpa_overrides o ON o.student_id=s.id ORDER BY s.roll_number');
 const [enrollments]=await pool.query(`SELECT e.*,c.course_code,c.course_name,c.credits,COALESCE(CONCAT(cl.code,' · ',g.name),cs.section_name) section_name,cs.section_number,cs.faculty_name,cs.classroom,cs.schedule FROM enrollments e JOIN courses c ON c.id=e.course_id JOIN course_sections cs ON cs.id=e.section_id LEFT JOIN section_clusters m ON m.section_id=cs.id LEFT JOIN cluster_groups g ON g.id=m.group_id LEFT JOIN academic_clusters cl ON cl.id=g.cluster_id`);
 res.json({success:true,count:students.length,students:students.map(s=>({id:s.id,rollNumber:s.roll_number,fullName:s.full_name,email:s.email,phone:s.phone,department:s.department,program:s.program,year:s.year_level,...formatStudent(s),attendanceRate:Number(s.attendance_rate),completedCredits:Number(s.completed_credits),totalCredits:s.total_credits,activeCoursesCount:enrollments.filter(e=>e.student_id===s.id&&e.status==='Enrolled').length,droppedCoursesCount:enrollments.filter(e=>e.student_id===s.id&&e.status==='Dropped').length,enrollments:enrollments.filter(e=>e.student_id===s.id).map(e=>({courseId:e.course_id,courseCode:e.course_code,courseName:e.course_name,credits:e.credits,sectionId:e.section_id,sectionName:e.section_name,sectionNumber:e.section_number,facultyName:e.faculty_name,classroom:e.classroom,schedule:e.schedule,status:e.status,enrolledAt:e.enrolled_at}))}))});
}));
router.get('/enrollments',asyncRoute(async(req,res)=>{const [rows]=await pool.query(`SELECT e.*,s.full_name,s.roll_number,s.department,c.course_code,c.course_name,c.credits,COALESCE(CONCAT(cl.code,' · ',g.name),cs.section_name) section_name,cs.section_number,cs.faculty_name,cs.classroom,cs.schedule FROM enrollments e JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id JOIN course_sections cs ON cs.id=e.section_id LEFT JOIN section_clusters m ON m.section_id=cs.id LEFT JOIN cluster_groups g ON g.id=m.group_id LEFT JOIN academic_clusters cl ON cl.id=g.cluster_id ORDER BY e.enrolled_at DESC`);res.json({success:true,enrollments:rows.map(e=>({id:e.id,studentId:e.student_id,studentName:e.full_name,rollNumber:e.roll_number,studentDepartment:e.department,courseId:e.course_id,courseCode:e.course_code,courseName:e.course_name,credits:e.credits,sectionId:e.section_id,sectionName:e.section_name,sectionNumber:e.section_number,facultyName:e.faculty_name,classroom:e.classroom,schedule:e.schedule,status:e.status,enrolledAt:e.enrolled_at}))});}));
router.post('/enrollments/drop',asyncRoute(async(req,res)=>res.json(await drop(text(req.body.studentId,'Student ID',50),text(req.body.courseId,'Course ID',50)))));
router.get('/faculty',asyncRoute(async(req,res)=>{const [faculty]=await pool.query('SELECT * FROM faculty');const [sections]=await pool.query(`SELECT cs.*,c.course_code,c.course_name,(SELECT COUNT(*) FROM enrollments e WHERE e.section_id=cs.id AND e.status='Enrolled') AS enrolled_students FROM course_sections cs JOIN courses c ON c.id=cs.course_id`);res.json({success:true,faculty:faculty.map(f=>({id:f.id,facultyId:f.faculty_id,fullName:f.full_name,designation:f.designation,department:f.department,email:f.email,phone:f.phone,office:f.office,qualification:f.qualification,coursesTaught:f.courses_taught,avatarInitials:f.avatar_initials,assignedSections:sections.filter(s=>s.faculty_id===f.id).map(s=>({sectionId:s.id,sectionName:s.section_name,courseCode:s.course_code,courseName:s.course_name,classroom:s.classroom,schedule:s.schedule,enrolledStudents:s.enrolled_students}))}))});}));
router.get('/audit',asyncRoute(async(req,res)=>{const [audit]=await pool.query('SELECT * FROM enrollment_audit_log ORDER BY log_id DESC LIMIT 200');res.json({success:true,audit});}));
router.get('/waitlist',asyncRoute(async(req,res)=>{const [waitlist]=await pool.query(`SELECT w.*,s.full_name,c.course_name,cs.section_name FROM waitlist w JOIN students s ON s.id=w.student_id JOIN courses c ON c.id=w.course_id JOIN course_sections cs ON cs.id=w.section_id WHERE w.status='Waiting' ORDER BY w.id`);res.json({success:true,waitlist});}));
router.put('/grades',asyncRoute(async(req,res)=>{
 const student=text(req.body.studentId,'Student ID',50),course=text(req.body.courseId,'Course ID',50);
 const result=calculateGrade(req.body.internalMarks,req.body.midtermMarks,req.body.finalMarks);
 const conn=await pool.getConnection();try{
  await conn.beginTransaction();await conn.query('SELECT id FROM course_sections ORDER BY id FOR UPDATE');
  const [enrolled]=await conn.execute("SELECT id FROM enrollments WHERE student_id=? AND course_id=? AND status IN('Enrolled','Completed') FOR UPDATE",[student,course]);if(!enrolled.length)throw new ApiError(409,'Student must be enrolled in this course before grades can be published.');
  await conn.execute(`INSERT INTO grades(student_id,course_id,internal_marks,midterm_marks,final_marks,total_marks,grade,grade_points)VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE internal_marks=VALUES(internal_marks),midterm_marks=VALUES(midterm_marks),final_marks=VALUES(final_marks),total_marks=VALUES(total_marks),grade=VALUES(grade),grade_points=VALUES(grade_points)`,[student,course,req.body.internalMarks,req.body.midtermMarks,req.body.finalMarks,result.total,result.grade,result.points]);
  await conn.execute('INSERT INTO notifications(id,student_id,title,message,category)VALUES(?,?,?,?,?)',[randomUUID(),student,'Grades published',`${course}: ${result.total}/100, grade ${result.grade}.`,'academic']);
  await conn.execute(`INSERT INTO enrollment_audit_log(student_id,course_id,action_type,remarks)VALUES(?,?,'GRADE_UPDATED',?)`,[student,course,`Published by ${req.user.id}: ${result.grade}`]);
  await conn.commit();res.json({success:true,message:'Marks published. GPA and earned credits are recalculated from grade records.',result});
 }catch(e){await conn.rollback();throw e;}finally{conn.release();}
}));
router.put('/attendance',asyncRoute(async(req,res)=>{
 const student=text(req.body.studentId,'Student ID',50),course=text(req.body.courseId,'Course ID',50),date=req.body.sessionDate;
 if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||typeof req.body.present!=='boolean')throw new ApiError(400,'Provide a valid date and boolean present value.');
 if(date>new Date().toISOString().slice(0,10))throw new ApiError(400,'Attendance cannot be recorded in the future.');
 const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query('SELECT id FROM course_sections ORDER BY id FOR UPDATE');const [active]=await conn.execute("SELECT id FROM enrollments WHERE student_id=? AND course_id=? AND status='Enrolled'",[student,course]);if(!active.length)throw new ApiError(409,'Attendance needs an active enrollment.');await conn.execute('INSERT INTO attendance(student_id,course_id,session_date,present)VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE present=VALUES(present)',[student,course,date,req.body.present]);await conn.commit();res.json({success:true,message:'Attendance recorded.'});}catch(e){await conn.rollback();throw e;}finally{conn.release();}
}));
router.get('/analytics',asyncRoute(async(req,res)=>{const [analytics]=await pool.query(`WITH ranked AS (SELECT v.student_id,v.roll_number,v.full_name,v.department,v.total_enrolled_courses,v.current_semester_credits,v.average_marks_obtained,COALESCE(o.value,v.current_gpa) current_gpa,v.current_gpa calculated_gpa,IF(o.student_id IS NULL,'calculated','admin') cgpa_source,v.completed_credits,v.semester_gpa,v.attendance_rate,DENSE_RANK() OVER(ORDER BY COALESCE(o.value,v.current_gpa) DESC) AS academic_rank FROM v_student_academic_summary v LEFT JOIN cgpa_overrides o ON o.student_id=v.student_id) SELECT * FROM ranked ORDER BY academic_rank,roll_number`);res.json({success:true,analytics});}));
export default router;
