import React,{useState} from 'react';import {Link} from 'react-router-dom';import {useApp} from '../context/AppContext';import ClusterCards from '../components/ClusterCards';
export default function Clusters(){const {clusters,currentUser:u,selectCluster}=useApp();const [busy,setBusy]=useState(false);const active=clusters.filter(c=>c.semester===u.semester);const selected=active.find(c=>c.id===u.clusterId);
 const choose=async id=>{setBusy(true);try{await selectCluster(id);}finally{setBusy(false);}};
 return <div><header className="pro-hero"><span className="pro-eyebrow">ONE COHORT. EVERY SUBJECT.</span><h1>Your academic cluster</h1><p>Choose one of four clusters. Pick any available section inside that cluster for each subject.</p><div className="pro-pill-row"><span>{u.semester}</span><span>{selected?selected.name:'Selection pending'}</span><span>{u.clusterLocked?'Locked for this semester':'Choose before enrolling'}</span></div></header>
 <div className="cluster-notice"><strong>{u.clusterLocked?'Your cluster is locked':'How cluster enrollment works'}</strong><span>{u.clusterLocked?'All future subjects must stay in this cluster. Contact the admin if a change is required.':'You may change your choice until your first enrollment or waitlist entry. Enrollment then locks it for the semester.'}</span></div>
 <ClusterCards clusters={active} selectedId={u.clusterId} locked={u.clusterLocked} busy={busy} onSelect={choose}/>
 {selected&&<section className="pro-card" style={{marginTop:24}}><div className="pro-card-top"><h2>Subjects in {selected.name}</h2><Link className="btn btn-primary" to="/planner">Plan your courses</Link></div><div className="cluster-subjects">{[...new Map(selected.sections.map(s=>[s.course_id,s])).values()].map(s=><Link key={s.course_id} to={`/courses/${s.course_id}`}><span className="course-code-pill">{s.course_code}</span><strong>{s.course_name}</strong><span>{selected.groups.length} section choices</span></Link>)}</div></section>}
 </div>;
}
