import {Link} from 'react-router-dom';
import React,{useState} from 'react';import {useApp} from '../context/AppContext';import api from '../services/api';
export default function Planner(){const {courses,currentUser,enrolledCourses,waitlist,enrollCourse,cancelWaitlist,showToast}=useApp();const [selected,setSelected]=useState({}),[busy,setBusy]=useState(null),[checks,setChecks]=useState({});
 const courseSection=c=>c.sections?.find(s=>s.id===selected[c.id])?.id||c.sections?.[0]?.id;
 const check=async c=>{try{const result=await api.enrollments.eligibility(c.id,courseSection(c));setChecks(p=>({...p,[c.id]:result}));}catch(e){showToast(e.message,'error');}};
 const submit=async(c,queue=false)=>{setBusy(c.id);try{await enrollCourse(c.id,courseSection(c),queue);setChecks({});}finally{setBusy(null);}};
 if(!currentUser.clusterId)return <div className="pro-card"><h1>Choose your cluster</h1><p>All subjects must be enrolled within one academic cluster.</p><Link className="btn btn-primary" to="/clusters">View the four clusters</Link></div>;
 const credits=enrolledCourses.reduce((n,c)=>n+Number(c.credits),0);
 return <div><div className="pro-hero"><span className="pro-eyebrow">YOUR SEMESTER, YOUR PLAN</span><h1>Enrollment planner</h1><p>Choose a section, check eligibility and build a schedule that works.</p><div className="pro-pill-row"><span>{credits} / 24 term credits</span><span>{enrolledCourses.length} active courses</span><span>{waitlist.length} waiting</span></div></div><div className="pro-grid">{courses.map(c=>{const active=enrolledCourses.find(e=>e.id===c.id);const section=c.sections?.find(s=>s.id===courseSection(c));const waiting=waitlist.find(w=>w.course_id===c.id);return <article className="pro-card" key={c.id}><div className="pro-card-top"><span className="course-code-pill">{c.courseCode}</span><span className="badge badge-neutral">{c.credits} credits</span></div><h2>{c.courseName}</h2><p className="pro-muted">{c.description}</p><label className="pro-field">Section<select value={courseSection(c)||''} onChange={e=>{setSelected(p=>({...p,[c.id]:e.target.value}));setChecks(p=>({...p,[c.id]:null}));}}>{c.sections?.map(s=><option key={s.id} value={s.id}>{s.sectionName} · {s.availableSeats} / {s.totalSeats} seats open</option>)}</select></label><div className="pro-schedule"><strong>{section?.schedule}</strong><span>{section?.classroom} · {section?.facultyName}</span></div><p className="pro-muted">Prerequisites: {c.prerequisites||'None'}</p>{active&&<p className="pro-good">Enrolled in {active.sectionName}</p>}{waiting&&<p className="pro-warning">Waiting for {waiting.section_name} · queue position {waiting.position}</p>}{checks[c.id]&&<p className={checks[c.id].eligible?'pro-good':'pro-warning'}>{checks[c.id].eligible?'Eligible: prerequisites, conflicts and credit limit checked.':checks[c.id].reason}</p>}<div className="pro-actions"><button className="btn btn-secondary" disabled={!section} onClick={()=>check(c)}>Check eligibility</button>{!waiting&&<button className="btn btn-primary" disabled={busy!==null||!section||active?.sectionId===section?.id} onClick={()=>submit(c,!active&&section?.availableSeats<=0)}>{busy===c.id?'Saving…':active?(active.sectionId===section?.id?'Current section':'Switch section'):section?.availableSeats<=0?'Join waitlist':'Enroll'}</button>}</div></article>;})}</div><section className="pro-card" style={{marginTop:24}}><h2>Your waitlist</h2><p className="pro-muted">Eligible waiting students are automatically enrolled when a seat is released. Queue order is first come, first served among eligible students.</p>{waitlist.length===0?<p>No active waitlist entries.</p>:waitlist.map(w=><div className="pro-list-row" key={w.id}><div><strong>{w.course_name}</strong><p>{w.section_name} · Position {w.position}</p></div><button className="btn btn-danger btn-sm" onClick={()=>cancelWaitlist(w.id)}>Leave waitlist</button></div>)}</section></div>;
}
