import React,{useState,useEffect} from 'react';import {useApp} from '../../context/AppContext';import api from '../../services/api';import ClusterCards from '../../components/ClusterCards';
export default function AdminClusters(){const {clusters,refreshBackendData,showToast}=useApp();const [selected,setSelected]=useState('CLUSTER-1'),[name,setName]=useState(''),[description,setDescription]=useState(''),[audit,setAudit]=useState([]),[busy,setBusy]=useState(false);const c=clusters.find(c=>c.id===selected)||clusters[0];
 useEffect(()=>{setName(c?.name||'');setDescription(c?.description||'');},[c?.id,c?.name,c?.description]);const loadAudit=async()=>{try{setAudit((await api.clusters.audit()).audit);}catch(e){showToast(e.message,'error');}};useEffect(()=>{loadAudit();},[]);
 const save=async fn=>{setBusy(true);try{await fn();await refreshBackendData();await loadAudit();showToast('Cluster settings saved.','success');}catch(e){showToast(e.message,'error');}finally{setBusy(false);}};
 return <div><header className="pro-hero"><span className="pro-eyebrow">COHORTS & COURSE OFFERINGS</span><h1>Cluster management</h1><p>Four academic clusters. Manage section groups and keep each student's subjects in one cohort.</p></header><ClusterCards clusters={clusters} admin/>
 {c&&<section className="pro-card" style={{marginTop:24}}><div className="pro-card-top"><h2>Manage {c.code}</h2><select aria-label="Manage cluster" value={c.id} onChange={e=>setSelected(e.target.value)}>{clusters.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="cluster-edit-grid"><label className="pro-field">Cluster name<input value={name} maxLength="100" onChange={e=>setName(e.target.value)}/></label><label className="pro-field">Description<input value={description} maxLength="255" onChange={e=>setDescription(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||!name.trim()} onClick={()=>save(()=>api.clusters.update(c.id,{name,description}))}>Save cluster</button></div><div className="cluster-edit-grid">{c.groups.map(g=><GroupEditor key={g.id} group={g} busy={busy} save={save}/>)}</div><h3>Course offerings</h3><p className="pro-muted">Sections with enrollment history cannot be moved. Empty offerings can be reassigned to another group in this semester.</p><div className="roster-table"><table><thead><tr><th>Subject</th><th>Group assignment</th><th>Schedule</th><th>Seats</th></tr></thead><tbody>{c.sections.map(s=><tr key={s.id}><td><strong>{s.course_name}</strong><small>{s.course_code} · {s.faculty_name}</small></td><td><select aria-label={`Group for ${s.id}`} value={s.group_id} disabled={busy} onChange={e=>save(()=>api.clusters.assignSection(s.id,e.target.value))}>{clusters.filter(x=>x.semester===c.semester).flatMap(x=>x.groups.map(g=><option key={g.id} value={g.id}>{x.code} · {g.name}</option>))}</select></td><td>{s.schedule}<small>{s.classroom}</small></td><td>{s.filled_seats} / {s.total_seats}</td></tr>)}</tbody></table></div></section>}
 <section className="pro-card" style={{marginTop:24}}><h2>Academic change history</h2>{audit.length?audit.slice(0,12).map(a=><div className="pro-list-row" key={a.id}><div><strong>{a.full_name||a.student_id} · {a.action.replaceAll('_',' ')}</strong><p>{a.old_value??'Unset'} → {a.new_value??'Calculated'} · {a.reason}</p></div><small>{new Date(a.created_at).toLocaleString()}</small></div>):<p className="pro-muted">CGPA and cluster changes appear here.</p>}</section></div>;
}
function GroupEditor({group,busy,save}){const [name,setName]=useState(group.name);useEffect(()=>setName(group.name),[group.name]);return <label className="pro-field">Section group<input value={name} maxLength="50" onChange={e=>setName(e.target.value)}/><button className="btn btn-outline btn-sm" disabled={busy||!name.trim()||name===group.name} onClick={()=>save(()=>api.clusters.renameGroup(group.id,name))}>Rename group</button></label>;}
