import React,{useEffect,useState} from 'react';import api from '../../services/api';import {useApp} from '../../context/AppContext';import Modal from '../../components/Modal';
export default function AdminStudents(){const {clusters,showToast,refreshBackendData}=useApp();const [students,setStudents]=useState([]),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState(null),[value,setValue]=useState(''),[reason,setReason]=useState(''),[cluster,setCluster]=useState(''),[expanded,setExpanded]=useState(null),[busy,setBusy]=useState(false);
 const load=async()=>{try{setError('');setStudents((await api.admin.getStudents()).students);}catch(e){setError(e.message);}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 const visible=students.filter(s=>(!filter||s.clusterId===filter)&&`${s.fullName} ${s.rollNumber} ${s.email}`.toLowerCase().includes(search.toLowerCase()));
 const edit=s=>{setEditing(s);setValue(s.cgpaSource==='admin'?String(s.currentGpa):'');setReason('');setCluster(s.clusterId||'');};
 const save=async kind=>{setBusy(true);try{if(kind==='cgpa')await api.clusters.saveCgpa(editing.id,value.trim()===''?null:Number(value),reason);else await api.clusters.select(editing.id,cluster,reason);showToast(kind==='cgpa'?'CGPA saved.':'Cluster saved.','success');await load();await refreshBackendData();setEditing(null);}catch(e){showToast(e.message,'error');}finally{setBusy(false);}};
 const exportRoster=()=>{const cell=v=>{let x=String(v??'');if(/^[=+@-]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"';};const rows=[['Roll number','Student','Cluster','CGPA','CGPA source','Active subjects'],...visible.map(s=>[s.rollNumber,s.fullName,s.clusterName||'Unassigned',s.currentGpa,s.cgpaSource,s.enrollments.filter(e=>e.status==='Enrolled').map(e=>e.courseCode+' '+e.sectionName).join('; ')])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='Student-Roster.csv';a.click();URL.revokeObjectURL(url);};
 return <div><header className="pro-hero"><span className="pro-eyebrow">ACADEMIC ADMINISTRATION</span><h1>Student directory</h1><p>See every student, their subjects, cluster and academic standing. Manage official CGPA with a recorded reason.</p><div className="pro-pill-row"><span>{students.length} students</span><span>{students.filter(s=>!s.clusterId).length} unassigned</span><span>{students.filter(s=>s.cgpaSource==='admin').length} official CGPA entries</span></div></header>
 <div className="roster-toolbar"><input aria-label="Search students" placeholder="Search name, roll number or email" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by cluster" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All clusters</option>{clusters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-secondary" onClick={load}>Refresh</button><button className="btn btn-primary" onClick={exportRoster}>Export roster</button></div>
 {error&&<p className="pro-warning" role="alert">{error}</p>}<section className="pro-card roster-table"><table><thead><tr><th>Student</th><th>Cluster</th><th>CGPA</th><th>Courses</th><th>Credits</th><th>Attendance</th><th>Actions</th></tr></thead><tbody>{visible.map(s=><React.Fragment key={s.id}><tr><td><strong>{s.fullName}</strong><small>{s.rollNumber} · {s.email}</small></td><td><span className="badge badge-neutral">{s.clusterName||'Not chosen'}</span><small>{s.clusterLocked?'Semester locked':'Selection open'}</small></td><td><strong>{Number(s.currentGpa).toFixed(2)}</strong><small>{s.cgpaSource==='admin'?'Admin-entered':'Calculated from grades'}</small></td><td><button className="course-count-btn" onClick={()=>setExpanded(expanded===s.id?null:s.id)}>{s.activeCoursesCount} active ▾</button></td><td>{s.completedCredits} / {s.totalCredits}</td><td><span className={s.attendanceRate&&s.attendanceRate<75?'pro-warning':'pro-good'}>{Number(s.attendanceRate).toFixed(1)}%</span></td><td><button className="btn btn-outline btn-sm" onClick={()=>edit(s)}>Edit academic record</button></td></tr>{expanded===s.id&&<tr><td colSpan="7"><div className="student-course-grid">{s.enrollments.map(e=><article key={e.courseId}><span className="course-code-pill">{e.courseCode}</span><strong>{e.courseName}</strong><span>{e.sectionName} · {e.status} · {e.credits} credits</span><small>{e.schedule} · {e.facultyName}</small></article>)}{!s.enrollments.length&&<p>No course enrollments yet.</p>}</div></td></tr>}</React.Fragment>)}</tbody></table>{!visible.length&&<p className="pro-muted">{loading?'Loading students…':'No students match your search.'}</p>}</section>
 <Modal isOpen={Boolean(editing)} onClose={()=>!busy&&setEditing(null)} title={`Academic record · ${editing?.fullName||''}`}><p className="pro-muted">{editing?.rollNumber} · Calculated GPA: {Number(editing?.calculatedGpa||0).toFixed(2)}</p><label className="pro-field">Official CGPA (0–10)<input type="number" min="0" max="10" step="0.01" value={value} placeholder="Leave empty to use calculated GPA" onChange={e=>setValue(e.target.value)}/></label><label className="pro-field">Current-semester cluster<select value={cluster} onChange={e=>setCluster(e.target.value)}><option value="">Choose a cluster</option>{clusters.filter(c=>c.semester===editing?.semester).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="pro-field">Reason for this change<textarea rows="3" maxLength="255" value={reason} onChange={e=>setReason(e.target.value)} placeholder="For example: verified transcript from previous semesters"/></label><p className="pro-muted">Blank CGPA restores the grade-derived value. Cluster changes require no active or completed current-semester enrollments and no waiting entries.</p><div className="pro-actions"><button className="btn btn-primary" disabled={busy||!reason.trim()} onClick={()=>save('cgpa')}>{busy?'Saving…':'Save CGPA'}</button><button className="btn btn-secondary" disabled={busy||!reason.trim()||!cluster||cluster===editing?.clusterId} onClick={()=>save('cluster')}>Update cluster</button></div></Modal>
 </div>;
}
